name: lint

on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Shared steps
      - uses: actions/checkout@v1
      - name: Install python
        uses: actions/setup-python@v1
      - name: Generate cache key PY
        run:
          echo "::set-env name=PY::${{ runner.os }} $(python -VV | sha256sum | cut -d' '
          -f1) ${{ hashFiles('pyproject.toml') }} ${{ hashFiles('poetry.lock') }}"
      - uses: actions/cache@v1
        with:
          path: .venv
          key: venv ${{ env.PY }}
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: pre-commit ${{ env.PY }} ${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pip install pipx
      - name: Generate cache key PIPX
        run: echo "::set-env name=PIPX::$(pipx --version | sha256sum | cut -d' ' -f1)"
      - uses: actions/cache@v1
        with:
          path: ~/.local/pipx/venvs
          key: pipx ${{ env.PY }} ${{ env.PIPX }}
      - uses: actions/cache@v1
        with:
          path: ~/.local/bin
          key: local-bin ${{ env.PY }} ${{ env.PIPX }}
      - name: Patch $PATH
        run: echo "::set-env name=PATH::$HOME/.local/bin:$PATH"
      - run: pipx install --force invoke
      - run: pipx install --force poetry
      - run: pipx ensurepath
      - run: invoke develop

      # Specific steps for this action
      - run: invoke lint
