name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      pytest_addopts:
        description:
          Extra options for pytest; use -vv for full details; see
          https://docs.pytest.org/en/latest/example/simple.html#how-to-change-command-line-options-defaults
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PYTEST_ADDOPTS: ${{ github.event.inputs.pytest_addopts }}
  PYTHONIOENCODING: "UTF-8"
  DOODBA_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    steps:
      - uses: &checkout-action actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        name: Checkout project
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.11"
      - uses: tox-dev/action-pre-commit-uv@e09b8958484dfe71f4ac3bc7afb230ba506402ec # v1.0.5

  test:
    runs-on: ubuntu-latest
    needs: pre-commit
    strategy:
      matrix:
        odoo-version: ["19.0"]
        python-version: ["3.12"]
        traefik-version: [3]
        include:
          - odoo-version: "18.0"
            python-version: "3.10"
            traefik-version: 2
          - odoo-version: "18.0"
            python-version: "3.11"
            traefik-version: 3
          - odoo-version: "17.0"
            python-version: "3.10"
            traefik-version: 2
          - odoo-version: "17.0"
            python-version: "3.10"
            traefik-version: 3
          - odoo-version: "16.0"
            python-version: "3.10"
            traefik-version: 2
          - odoo-version: "16.0"
            python-version: "3.10"
            traefik-version: 3
          - odoo-version: "15.0"
            python-version: "3.9"
            traefik-version: 2
          - odoo-version: "15.0"
            python-version: "3.9"
            traefik-version: 3
          - odoo-version: "14.0"
            python-version: "3.9"
            traefik-version: 3
          - odoo-version: "13.0"
            python-version: "3.9"
            traefik-version: 3
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      # Shared steps
      - uses: *checkout-action
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@16feee727cbdc83b6a014e6cc26fec4a79bcf30c # v2.2.0
        with:
          version: v2.40.3
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
          # Install a specific version of uv.
          version: "0.12.5"
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      # Precreate shared networks to avoid race conditions
      - run: docker network create inverseproxy_shared
      - run: docker network create globalwhitelist_shared
      # Let tests issue git commits
      - run: git config --global user.name CI
      - run: git config --global user.email CI@GITHUB
      # Run all tests, which includes linters
      - run: uv run pytest tests -m "not sequential"
        env:
          SELECTED_ODOO_VERSIONS: ${{ matrix.odoo-version }}
          TRAEFIK_VERSION: ${{ matrix.traefik-version }}
      - run: uv run pytest tests --dist no -m "sequential"
        env:
          SELECTED_ODOO_VERSIONS: ${{ matrix.odoo-version }}
          TRAEFIK_VERSION: ${{ matrix.traefik-version }}
